FROM ubuntu:18.04

MAINTAINER ShangzhongLi <Shangzhong.Li@pfizer.com>


ENV PATH /opt/miniconda/bin:$PATH
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# install conda
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install -y wget libpng-dev libssl-dev \
     gcc make libssl1.0.0 && \
     cd opt && \
     wget --quiet https://repo.continuum.io/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh && \
     chmod 755 Miniconda3-py38_4.10.3-Linux-x86_64.sh && \
     ./Miniconda3-py38_4.10.3-Linux-x86_64.sh -b -p /opt/miniconda && \
     rm Miniconda3-py38_4.10.3-Linux-x86_64.sh && \     
     eval "$(/opt/miniconda/bin/conda shell.bash hook)" && \
     pip3 install crossmap && \
     pip3 install pandas && \
     conda install -y -c bioconda tabix && \
     wget https://raw.githubusercontent.com/lis262/Pipeline/master/GWAS/crossmap_gwas_summary.py && \
     wget https://raw.githubusercontent.com/lis262/Pipeline/master/GWAS/crossmap_bed_like_format.py && \
     sed -i 's/if len(fields)<12/if len(fields)>=3/g' /opt/miniconda/lib/python3.8/site-packages/cmmodule/mapbed.py && \
     sed -i 's/if len(fields)==12 or len(fields)==20/if len(fields)<0/g' /opt/miniconda/lib/python3.8/site-packages/cmmodule/mapbed.py

RUN  wget http://ftp.ensembl.org/pub/assembly_mapping/homo_sapiens/GRCh37_to_GRCh38.chain.gz && \
	 wget http://ftp.ensembl.org/pub/assembly_mapping/homo_sapiens/GRCh38_to_GRCh37.chain.gz && \
	 wget http://hgdownload.soe.ucsc.edu/goldenPath/hg38/liftOver/hg38ToHg19.over.chain.gz && \
	 wget http://hgdownload.soe.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz

CMD ["/bin/bash"]

